services:
  - type: web
    name: ia-editor-video
    env: python
    buildCommand: |
      # Instala dependências do sistema
      apt-get update && apt-get install -y ffmpeg python3-dev build-essential zlib1g-dev libjpeg-dev
      # Instala dependências Python
      pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn app:app --timeout 300
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MAX_UPLOAD_SIZE
        value: 16777216  # 16MB em bytes
